daysUntilStale: 15
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale due to 15 days of inactivity.
  It will be closed in 7 days if no further activity occurs.
closeComment: >
  Closing this issue due to inactivity. Feel free to reopen if it's still relevant.