name: "Mark stale issues and pull requests"

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  issues:
    types:
      - opened
      - edited
      - reopened
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: "This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs."
          close-issue-message: "Closing this issue due to inactivity. Feel free to reopen if needed."
          stale-pr-message: "This PR has been automatically marked as stale due to inactivity."
          close-pr-message: "Closing this PR due to inactivity."
          exempt-issue-labels: "pinned,security"
          exempt-pr-labels: "pinned,security"
          stale-label: "stale"